### PR TITLE
set the default max value for the additional option to 1

### PR DESCRIPTION
**Pull request by vladimir-8**
Fixes: https://github.com/coopcycle/coopcycle-web/issues/3861

### CODE REVIEW

**Comment by Atala** [comment]
image


hello some small remarks on the product option form :
- the "no max value" checkbox should be at the same level than the number inputs
- ticking the checkbox should hide the "max value" input not disable it
- once the product is saved, when you untick "max value" then value in the "max" input is INF, should be 1 no?

max-value

**Review by Atala — APPROVED** [review]
see my comment on the PR

I guess you have a lot on your plate; so if it takes you too long ignore the comment and merge directly :)

**Comment by vladimir-8** [comment]
Thanks for the review! The idea was to make a quick fix, so indeed I don't want to spend a lot of time on the various improvements.

But this seems directly related to the original issue. I'll implement it:

> once the product is saved, when you untick "max value" then value in the "max" input is INF, should be 1 no?

**Comment by vladimir-8** [comment]
> once the product is saved, when you untick "max value" then value in the "max" input is INF, should be 1 no?

@Atala I implemented this. Please take a look

**Review by Atala — CHANGES_REQUESTED** [review]
If i go from INFINITE to 1, I am under the impression it is not correctly set. See GIF below. correct me if i am wrong!

I am in holyday next week, so please fix and merge directly! 

max-value-not-set

**Comment by vladimir-8** [comment]
It happens because the menu page is cached. If you want to test it immediately you can temporary remove the cache element from https://github.com/coopcycle/coopcycle-web/blob/57da3a4974cc03750905f867b0767a0ace6df62f/templates/restaurant/index.html.twig#L194

**Comment by Atala** [comment]
OK thanks I didnt know that, sorry for the false alert

**Pull request merged**
