### PR TITLE
Added task creation date to API

### PR DESCRIPTION
**Pull request by biologeek**
Is used for billing fast deliveries

### CODE REVIEW

**Comment by alexsegura** [comment]
This seems weird to allow this 🤔

**Comment by alexsegura** [comment]
Can you explain a little bit more the use case? How come are you creating fast deliveries via the API?

**Comment by biologeek** [comment]
Hi Mex, we have a customer for which orders delivered within 1 hour have an extra line on the bill. We are using another software to process deliveries and bill customers. So I need to have the delivery creation date (read-only of course) to calculate delivery delay and add or not the extra 3 €

**Comment by alexsegura** [comment]
My bad, I misread. I thought you wanted to allow the creation date to be set via POST.

**Review by alexsegura — APPROVED** [review]

**Comment by alexsegura** [comment]
Thank you @biologeek

**Pull request merged**
