### PR TITLE
Coder friendly import version

### PR DESCRIPTION
**Pull request by TheoPatros**
The merge is conditionned to validation by user community, due to changes in process.
It aims to harmonize import and export formats, toward the format used for export nowadays.

Do NOT merge both "Coder friendly import version" AND "User friendly export version"

### CODE REVIEW

**Comment by alexsegura** [comment]
Thank you for this pull request. 

Can we change this without a BC break? 
It should be easy to support _both_ `address` and `address.streetAddress`. 

Tests should stay green.

```
PHPUnit 7.4.0 by Sebastian Bergmann and contributors.
...............................................................  63 / 187 ( 33%)
............................................................... 126 / 187 ( 67%)
..................................EFEFEF.....................   187 / 187 (100%)
Time: 4.89 seconds, Memory: 104.50MB
There were 3 errors:
1) Tests\AppBundle\Utils\TaskSpreadsheetParserTest::testCsv
Exception: You must provide an ".streetAddress" or a "address.latlng" column
/home/travis/build/coopcycle/coopcycle-web/src/AppBundle/Utils/TaskSpreadsheetParser.php:188
/home/travis/build/coopcycle/coopcycle-web/src/AppBundle/Utils/TaskSpreadsheetParser.php:85
/home/travis/build/coopcycle/coopcycle-web/tests/AppBundle/Utils/TaskSpreadsheetParserTest.php:58
2) Tests\AppBundle\Utils\TaskSpreadsheetParserTest::testXlsx
Exception: You must provide an ".streetAddress" or a "address.latlng" column
/home/travis/build/coopcycle/coopcycle-web/src/AppBundle/Utils/TaskSpreadsheetParser.php:188
/home/travis/build/coopcycle/coopcycle-web/src/AppBundle/Utils/TaskSpreadsheetParser.php:85
/home/travis/build/coopcycle/coopcycle-web/tests/AppBundle/Utils/TaskSpreadsheetParserTest.php:81
3) Tests\AppBundle\Utils\TaskSpreadsheetParserTest::testOds
Exception: You must provide an ".streetAddress" or a "address.latlng" column
/home/travis/build/coopcycle/coopcycle-web/src/AppBundle/Utils/TaskSpreadsheetParser.php:188
/home/travis/build/coopcycle/coopcycle-web/src/AppBundle/Utils/TaskSpreadsheetParser.php:85
/home/travis/build/coopcycle/coopcycle-web/tests/AppBundle/Utils/TaskSpreadsheetParserTest.php:104
```

**Comment by TheoPatros** [comment]
Errors on lines 2323
`CypressError: Timed out retrying: Expected to find element: 'ul[role="listbox"]', but never found it. Queried from element: <div.ReactModal__Content.ReactModal__Content--after-open.ReactModal__Content--enter-address>`

2340
`CypressError: Timed out retrying: Expected to find element: '.react-autosuggest__section-container', but never found it. Queried from element: <div#react-autowhatever-1.react-autosuggest__suggestions-container.address-autosuggest__suggestions-container>`

2393
`CypressError: Timed out retrying: Expected to find content: '23 Avenue Claude Vellefaux, Paris, France' but never did.`

I don't think it's about the code this time

**Comment by alexsegura** [comment]
@TheoPatros it's normal when you open pull requests from a fork

**Comment by TheoPatros** [comment]
PR abandoned. To be continued at #2064 :)

**Pull request closed without merging**
