### PR TITLE
Add selenium & tests

### PR DESCRIPTION
**Pull request by freelibre**
This is a Work in progress for issue:
https://github.com/coopcycle/coopcycle-web/issues/391

With this you can log in a Selenium grid console with 2 browers (chrome & firefox):
http://localhost:4444/grid/console
An exemple test case is added in side format (exported from firefox selenium IDE)
A new npm package is added to launch side test from CLI

Next steps proposal:
- try to launch side-runner tests automatically and get result in grid thru VNC
- try to add it in Travis 
- try to add existing behat test

### CODE REVIEW

**Comment by alexsegura** [comment]
Thank you for this 👏

IMHO, the final goal is to have browser tests written in Behat/Gherkin language. 
I think this is more maintainable, and we can have access to the database, to create fixtures, for example. 

Selenium IDE can be cool, so that "random" users can help us write tests. 
I found [salmabenhadjali/gherkinator](https://github.com/salmabenhadjali/gherkinator) that allows to convert `*.ide` files to Gherkin language. 
A pretty nice workflow would be: 
- People create `*.ide` files without any knowledge of Gherkin
- We convert them to Gherkin language automatically

Actually, I would like to give a try to [symfony/panther](https://github.com/symfony/panther), it looks like it is way easier to use than full-stack Selenium. 
Let me try to setup `symfony/panther` on the project. It looks like it is not supported out of the box in Behat (see Behat/Symfony2Extension#145), but it should be easy.

**Comment by freelibre** [comment]
Thank you for your feeback. I think `*.ide` file will be deprecated soon so I've proposed `*.side` files generated by the new IDE version. It should be possible to then use [selenium-side-runner](https://www.npmjs.com/package/selenium-side-runner) to run tests. You are right such files generated are indeed more for people willing to contribute by adding some End 2 End scenario without lot of coding knowledge as it just needs the browser extension you can grab [firefox extension](https://addons.mozilla.org/fr/firefox/addon/selenium-ide/) for example and such tests could be generated and updated very quickly. I'm trying  behat/mink facebook\php webdriver to interface with selenium hub but your solution seems much wiser.

**Comment by alexsegura** [comment]
While digging around I came across [Zalenium](https://opensource.zalando.com/zalenium/)

- [zalando/zalenium](https://github.com/zalando/zalenium)
- [docker-selenium](https://github.com/elgalu/docker-selenium)

**Comment by freelibre** [comment]
Yes you are right Zalenium add more features. If you want I will change to Zalenium. I've just push the VNC support to current selenium install so now you can connect to a node `URL:5900` with a VNC client like VNCtiger or Remmina (the login password is : secret) and then you will be able to see the tests playing in a browser.

**Comment by alexsegura** [comment]
See #502

**Pull request closed without merging**
