### PR TITLE
add sudo to `docker-compose up` command

### PR DESCRIPTION
**Pull request by florentk**

### CODE REVIEW

**Comment by Atala** [comment]
Hey Florent,

You shouldn't need `sudo` to run the `docker-compose` command. Which platform are you on?

Aloïs

**Comment by florentk** [comment]
I have this error without `sudo` when I lauch  `docker-compose up` and `make install` :
`ERROR: Couldn't connect to Docker daemon at http+docker://localunixsocket - is it running?`

**Comment by florentk** [comment]
En faite, d'après la doc de Docker :+1: 

> If you would like to use Docker as a non-root user, you should now consider
> adding your user to the "docker" group with something like:
`sudo usermod -aG docker your-user`

**Comment by Atala** [comment]
Added instructions in b712b5a

**Pull request closed without merging**
