### PR TITLE
Renamed ApiUser to User

### LINKED ISSUE #218: Entity ApiUser should be called User
Simple, beautiful

### PR DESCRIPTION
**Pull request by johnnybigoode**
Fixes #218

### CODE REVIEW

**Comment by johnnybigoode** [comment]
Cypress tests seem to be failing. I've no idea what's the issue tho

**Comment by alexsegura** [comment]
Cypress tests fail because they are using GitHub secrets, which can't be read by people not belonging to the organization.
It's also "normal" 😅

**Comment by alexsegura** [comment]
I will double-check & merge tomorrow, but LGTM 👍

**Review by alexsegura — APPROVED** [review]

**Comment by alexsegura** [comment]
Thank you @johnnybigoode

**Pull request merged**
