### PR TITLE
Attach tasks to organizations

### LINKED ISSUE #1402: Ability to assign manually created tasks to a Store.
I see it as two tasks (1 pickup and 1 dropoff) that have been created before a Store existed on the platform, they can be assigned to a specific Store created at a later date and by assigning those two tasks an order is created.

### PR DESCRIPTION
**Pull request by alexsegura**
Fixes #1402

Under the hood, this pull request introduces Organizations (#1311) as the top level entity to represent a customer. 
Technically, tasks are attached to an Organization, and Stores & Restaurants too. However, the user interface still shows Stores/Restaurants, for backward compatibility. 

**TODO**

- [x] Attach task to store when created via API

This introduces a new view for tasks as a list, where it's possible to attach tasks to stores

multi-select-tasks

--- 

On the dashboard, when the task is attached to an organization (a store or a restaurant), it is displayed like this:

Capture d’écran 2020-09-15 à 13 42 28

### CODE REVIEW

**Comment by agichim** [comment]
If tasks are not linked together as an order they can still be attached under a store but will still be unlinked, right?

**Comment by alexsegura** [comment]
@agichim yes, they would still be unlinked, it would not "reconstruct" a delivery. 
Should we also allow to link tasks together into a delivery? It's #690

**Comment by agichim** [comment]
#690 is a great issue! I guess the ideal would be to link tasks into an order or not if you don't want to. But, as we discussed about not having tasks without stores, maybe tasks should always be linked into an order. I'm not sure yet about that.

**Comment by alexsegura** [comment]
@agichim no, tasks shouldn't enforced to be attached to an order, it couples too much things together between e-commerce & dispatch.
But being able to select some tasks, and "convert" them into an order, seems good.

**Comment by agichim** [comment]
Makes sense then!

**Review by agichim — APPROVED** [review]

**Comment by alexsegura** [comment]
Let's open another issue about being able to create orders from tasks.
It needs to be discussed a little bit to make it right 🙂

**Comment by agichim** [comment]
I'll check if there is an issue opened already. I feel I might have done it myself?

**Comment by agichim** [comment]
Here's the issue #1731

**Pull request merged**
