### PR TITLE
feat: disable automatic dispatch with a setting

### PR DESCRIPTION
**Pull request by Atala**

### CODE REVIEW

**Comment by alexsegura** [comment]
Can you fix the tests? 
It looks like we need to initialize the database config for Travis.

**Comment by alexsegura** [comment]
Actually, the problem is that on Travis, the automatic dispatch is tested by default, but it is disabled by default. Maybe for now we can disable those tests?

**Comment by Atala** [comment]
I have the tests running locally but timeout on travis... -> I need to investigate (no clue at the moment)

**Comment by alexsegura** [comment]
As we are going to deprecate this version of automatic dispatch, I close this PR. 

I hope you didn't lose to much time on this 😐

**Comment by Atala** [comment]
The code is still relevant no?

**Comment by alexsegura** [comment]
Yes, this is why I didn't delete the branch 😉

**Pull request closed without merging**
