### PR TITLE
Cleanup/simplify Dockerfile

### PR DESCRIPTION
**Pull request by Pandoraaa**
May fix some problems on Linux (#789)

### CODE REVIEW

**Comment by alexsegura** [comment]
Thank you for this. 

Definitely, I think the `umask(0000)` is the fix we need. A Symfony 4 front controller file looks like this: 

https://github.com/symfony/recipes/blob/7be9ee0bbaf2ee0a3fdcfffdb1567917290a36c3/symfony/framework-bundle/4.2/public/index.php

```

if ($_SERVER['APP_DEBUG']) {
    umask(0000);
    Debug::enable();
}
```

**Comment by alexsegura** [comment]
See #803

**Comment by alexsegura** [comment]
@Pandoraaa I rebased your commits and added some more.

Can you try again to see if it fixes your problems?

```
rm -rf vendor
rm -rf var/jwt
docker-compose down -v
docker-compose build php
docker-compose up
```

**Comment by alexsegura** [comment]
@Pandoraaa I think all remaining problems are fixed in #816

**Comment by Pandoraaa** [comment]
@alexsegura Oh yeah now everything works fine! 
Happy to see that the umask solution did the job :+1: 

I think the docker build could be optimized, it was sooooo long... :timer_clock:

**Comment by alexsegura** [comment]
Yeah what is long is compiling the PHP extensions. The simplest way to speed up the start of the containers would be to pre-build it, and upload it to Docker Hub.

**Pull request merged**
