### PR TITLE
Store consent in database

### LINKED ISSUE #2175: Enable GDPR consent for customers
Issue: Client's data cannot be used by delivery companies since they don't give their GRPD consent while ordering on the plateform. This data could really be usefull to send client satisfaction survey, contact specific clients as regards their preferences and reward them or propose them services that correspond to their needs (i.e. clients who make big orders, or order all the time at the same restaurant)

Proposal: 
a) Add GRPD consent in the client ordering process before they proceed to payment
b) Enable admin to have access to client database with the following datas:
- Number of order per week
- Name of the restaurants in which they ordered
- Date of the last order
- Average prices of ordered passed on the plateform
c) Give the possibility to activate an email sent to the client after the order is "completed" (terminée) in which the admin car add a link with a client satisfaction survey.

### PR DESCRIPTION
**Pull request by alexsegura**
Fixes #2175

Something like this:

Capture d’écran 2020-07-03 à 12 28 12

---

The technique used to store consent in database is inspired by [this Stack Exchange Law thread](https://law.stackexchange.com/questions/29190/gdpr-where-to-store-users-consent)

Useful info & more inspiration on [Countly docs](https://support.count.ly/hc/en-us/articles/360037441932-Web-analytics-JavaScript-#gdpr-consent-management)

**TODO**

- [ ] ~Manage the privacy policy agreement with OptinConsent~
- [ ] ~When a user has not given consent for privacy policy, show a banner with a link (for previous users)~
- [ ] ~In user profile, add a page to optin/optout from agreements~
- [ ] ~What happens if users optout?~ 
- [x] Allow toggling the feature via env variable

### CODE REVIEW

**Comment by lucasferraro** [comment]
This PR should be merged after this one https://github.com/coopcycle/coopcycle-web/pull/3161 is merged in `register-content` branch

**Comment by lucasferraro** [comment]
With this PR (and this https://github.com/coopcycle/coopcycle-web/pull/3161) now we are able to ask for optin consent to new and existing users, and then export users who have give their consent:

**Existing user agrees with only one optin**
https://user-images.githubusercontent.com/4819244/157558722-44b0efc9-b4aa-4cf8-adde-915cf22b59f8.mp4

**Registration user**
https://user-images.githubusercontent.com/4819244/157558734-ac953745-9264-4bf8-8974-3ea3d1a81e13.mp4

**Export feature**
https://user-images.githubusercontent.com/4819244/157558714-a771c8e0-ee67-46e5-ac6c-fb7932490d22.mp4

**Export Result**
[coopcycle-users-for-NEWSLETTER-.csv](https://github.com/coopcycle/coopcycle-web/files/8218985/coopcycle-users-for-NEWSLETTER-.csv)
[coopcycle-users-for-MARKETING-.csv](https://github.com/coopcycle/coopcycle-web/files/8218984/coopcycle-users-for-MARKETING-.csv)

**Comment by AdrienSICKLO** [comment]
Looks great!
In the video you uploaded, I see 2 things.
1- for existing users, the pop up might be better if something said "This pop up will appear only once to update your personal settings."
2- I would suggest we put receive "I agree to receive LocalCo-op / CoopCycle information/newsletter as well, not just "CoopCycle".

Fantastic in any case!

**Comment by alexsegura** [comment]
@AdrienSICKLO 

> 2- I would suggest we put receive "I agree to receive LocalCo-op / CoopCycle information/newsletter as well, not just "CoopCycle".

The name is dynamic, of course, it takes the name of the instance.

**Comment by lucasferraro** [comment]
@AdrienSICKLO @alexsegura 
> 1- for existing users, the pop up might be better if something said "This pop up will appear only once to update your personal settings."
Ok, I agree with this suggestion to give more context to the user.

Something that I was thinking before is if it would be "better" that the checkboxes appear as checked by default, because I guess in many cases users will click on submit button just to make the popup go away.
I've seen this behaviour in other webs where checkboxes for consent appear as checked by default, it's a bit annoying for me as user becuase it sounds to me like a trap :sweat_smile: but in terms of get more consent can be a good strategy.
What do you think?

**Comment by alexsegura** [comment]
@lucasferraro 

> it would be "better" that the checkboxes appear as checked by default

No, it's against GDPR 

https://eur-lex.europa.eu/legal-content/EN/ALL/?uri=CELEX%3A62017CJ0673

**Comment by alexsegura** [comment]
@AdrienSICKLO @lucasferraro 

I changed the wording a little bit. The texts can still be changed later.

Capture d’écran 2022-03-22 à 17 44 30

**Comment by lucasferraro** [comment]
> @lucasferraro
> 
> > it would be "better" that the checkboxes appear as checked by default
> 
> No, it's against GDPR
> 
> https://eur-lex.europa.eu/legal-content/EN/ALL/?uri=CELEX%3A62017CJ0673
> 
> > It should be noted in that regard that, according to recital 32 thereof, giving consent could include ticking a box when visiting an internet website. On the other hand, that recital expressly precludes ‘silence, pre-ticked boxes or inactivity’ from constituting consent
> 
> > Consent should be given by a clear affirmative act establishing a freely given, specific, informed and unambiguous indication of the data subject’s agreement to the processing of personal data relating to him or her, such as by a written statement, including by electronic means, or an oral statement. This could include ticking a box when visiting an internet website, choosing technical settings for information society services or another statement or conduct which clearly indicates in this context the data subject’s acceptance of the proposed processing of his or her personal data. Silence, pre-ticked boxes or inactivity should not therefore constitute consent. Consent should cover all processing activities carried out for the same purpose or purposes. When the processing has multiple purposes, consent should be given for all of them. If the data subject’s consent is to be given following a request by electronic means, the request must be clear, concise and not unnecessarily disruptive to the use of the service for which it is provided.

Wow, I didn't know that. Thanks for sharing.

**Pull request merged**
