### PR TITLE
Bump Nucleos to 2.x.

### LINKED ISSUE #3651: No visible error for a user when inputting erroneous information in fields to create a new user in the web
**Describe the bug**
When creating a new user profile from the web application, there are a number of possible errors such as using an email address that already is connected to a user profile, or inputting a password that is not sufficiently secure. When this happens, no error is shown, simply the page is refreshed. 

**To Reproduce**
1. Go to https://demo.coopcycle.org/register/
2. Input incorrect information (already used email address, or a bad password)
3. Try to create the user profile
4. See a refreshed page with no explanation of why it has not worked

**Expected behavior**
Like in the iOS application (video below), an error should appear that explains that
A. the profile has not been created
B. why 

**Screenshots**
web error
passwordallowsanything
232b-a03f-4e8f-833e-f00ab3b55b

iOS working

https://github.com/coopcycle/coopcycle-web/assets/77277854/2801b1cb-fe21-4066-b7a7-862cedbb6a8c

https://github.com/coopcycle/coopcycle-web/assets/77277854/c7314dd1-f823-4fc9-addf-e341aaad5039

### PR DESCRIPTION
**Pull request by alexsegura**
Done by following upgrade guides and fixing errors:
- https://github.com/nucleos/NucleosUserBundle/blob/2.3.x/UPGRADE-2.0.md
- https://github.com/nucleos/NucleosProfileBundle/blob/2.3.x/UPGRADE-2.0.md

This removes technical debt, and also fixes the problem of errors not properly mapped to fields when registering. 

Capture d’écran 2023-07-04 à 19 03 37

Fixes #3651

### CODE REVIEW

**Review by lucasferraro — CHANGES_REQUESTED** [review]
I'm facing some weird behavior when I try to login with existing accounts. I don't see any error, just keep in login page after enter credentials. Only when I reset the password the login works fine. Also if a create/register a new account I don't have any issues with that account. 
This is only happening with existing accounts. Do you have this problem too?


https://github.com/coopcycle/coopcycle-web/assets/4819244/68a0a1aa-6813-4063-9dc5-d8391faba9aa

Also, the label about "remember me" option seems like doesn't have the translation. The functionality seems to work fine. But I found this https://github.com/nucleos/NucleosUserBundle/pull/498

**Comment by alexsegura** [comment]
@lucasferraro thank you, nice catch. The login error is fixed in 1fe4abbc3c5117bfe98952deacf576b4cabf876d

I'm going to look to update usage of the remember me feature.

**Comment by alexsegura** [comment]
@lucasferraro remember me seems to continue working (the `REMEMBERME` cookie is created), I have just copied the missing translations in 0d1d961404334e9194820260ac170e02c7466cb2

**Review by lucasferraro — APPROVED** [review]
Now it seems to be working ok and looks good too.

**Comment by alexsegura** [comment]
When deploying an instance after this changes, all users are disconnected. It seems to be related with the remember me feature.

Capture d’écran 2023-07-20 à 12 45 28

**Comment by alexsegura** [comment]
Also we have this in the logs

Capture d’écran 2023-07-20 à 12 47 26

**Comment by alexsegura** [comment]
Users being disconnected after upgrade should be fixed in 3a7f24ac2baa32eed40b191fd8826edc823edffa

**Pull request merged**
