### PR TITLE
fix coding style respecting the symfony recommandations

### PR DESCRIPTION
**Pull request by clementtalleu**
Fix all coding style errors by respecting the php psr conventions :  

https://github.com/FriendsOfPHP/PHP-CS-Fixer

### CODE REVIEW

**Comment by alexsegura** [comment]
Thank you!

Can you please amend your commit with your actual Github email? 😄

**Comment by alexsegura** [comment]
You are right, we should add some coding style / code coverage tools. 
I've never used any of them, @clementtalleu do you have a tool to recommend? 
[Code climate](https://codeclimate.com/) looks nice.

**Comment by clementtalleu** [comment]
I amend my commit, it will be ok for the next ^^

I never used code climate but it seems good. I use phpstan and cs-fixer on local environment which are the most popular. With phpstan you can precise a specific level of rigor in our code. It's easy to config with travis.

phpstan : https://github.com/phpstan/phpstan

**Comment by alexsegura** [comment]
Merged in ee02ff9576adf1fd9c9c9c8806badf656ad2ccaa

**Comment by alexsegura** [comment]
Let's continue the discussion about coding style tools here #48

**Pull request closed without merging**
