### PR TITLE
rollback from latest version of osrm to 5.9.2

### PR DESCRIPTION
**Pull request by Ladias-Elie**

### CODE REVIEW

**Comment by alexsegura** [comment]
Oh you are right, we have freezed the version in production. 

However we are using `5.16.0` in production, can you set this version?

Also, the file `package-lock.json` shouldn't have changed.

**Comment by Ladias-Elie** [comment]
I tried several of them but 5.9.2 seems to be the only one working for me...

Here is the log for the 5.16.0:

```
osrm_1      | [warn] Missing/Broken File: /data/data.osrm.maneuver_overrides
osrm_1      | [error] Required files are missing, cannot continue
coopcycleweb_osrm_1 exited with code 1
```

any suggestions ?

**Comment by alexsegura** [comment]
Have you tried compiling it from scratch?

```
docker-compose build osrm
make osrm
```

**Comment by Ladias-Elie** [comment]
ok it worked. I close this PR, I will include the 5.16.0 in my next one.

**Pull request closed without merging**
